{"info": {"start_time": "Sunday, 09. December 2018 05:26:56PM", "end_time": "Sunday, 09. December 2018 05:26:56PM", "timedelta": 0, "attempts": 1, "final score": 20, "max score": 20}, "internal_log": [], "external_log": ["Running test: digital_root(1729)", "Correct!", "Running test: digital_root(356)", "Correct!", "Running on a hidden test.", "Correct!", "Running on a hidden test.", "Correct!", "Running on a hidden test.", "Correct!", "Running on a hidden test.", "Correct!", "CONGRATULATIONS! All the tests passed."], "score_sum": 20, "max_score": 20}
{"info": {"start_time": "Sunday, 09. December 2018 05:26:56PM", "end_time": "Sunday, 09. December 2018 05:26:56PM", "timedelta": 0, "attempts": 1, "final score": 0, "max score": 20}, "internal_log": [], "external_log": ["Running test: digital_root(1729)", "Error!\n  We expected: 1\n  We received: 5", "At least one of our tests above found a problem."], "score_sum": 0, "max_score": 20}
{"info": {"start_time": "Sunday, 09. December 2018 05:26:56PM", "end_time": "Sunday, 09. December 2018 05:26:56PM", "timedelta": 0, "attempts": 1, "final score": 0, "max score": 20}, "internal_log": [], "external_log": ["Running test: digital_root(1729)", "Exception raised!\nmodule 'digital_root3' has no attribute 'digital_root'", "At least one of our tests above found a problem."], "score_sum": 0, "max_score": 20}
{"info": {"start_time": "Sunday, 09. December 2018 05:26:56PM", "end_time": "Sunday, 09. December 2018 05:26:56PM", "timedelta": 0, "attempts": 1, "final score": 20, "max score": 20}, "internal_log": [], "external_log": ["Running test: hailstone(7)", "Correct!", "Running test: hailstone(13)", "Correct!", "Running on a hidden test.", "Correct!", "Running on a hidden test.", "Correct!", "Running on a hidden test.", "Correct!", "CONGRATULATIONS! All the tests passed."], "score_sum": 20, "max_score": 20}
{"info": {"start_time": "Sunday, 09. December 2018 05:26:56PM", "end_time": "Sunday, 09. December 2018 05:26:56PM", "timedelta": 0, "attempts": 1, "final score": 0, "max score": 20}, "internal_log": [], "external_log": ["Running test: hailstone(7)", "Error in line 2:\n  We expected: 22 is even, so I take half: 11.0\n  We received: 22 is even, so I take haaalf: 11.0", "At least one of our tests above found a problem."], "score_sum": 0, "max_score": 20}
{"info": {"start_time": "Sunday, 09. December 2018 05:26:56PM", "end_time": "Sunday, 09. December 2018 05:26:56PM", "timedelta": 0, "attempts": 1, "final score": 20, "max score": 20}, "internal_log": [], "external_log": ["Running test: hailstone(7)", "Correct!", "Running test: hailstone(13)", "Correct!", "Running on a hidden test.", "Correct!", "Running on a hidden test.", "Correct!", "Running on a hidden test.", "Correct!", "CONGRATULATIONS! All the tests passed."], "score_sum": 20, "max_score": 20}
{"info": {"start_time": "Sunday, 09. December 2018 05:26:56PM", "end_time": "Sunday, 09. December 2018 05:26:56PM", "timedelta": 0, "attempts": 1, "final score": 0, "max score": 20}, "internal_log": [], "external_log": ["Running test: hailstone(7)", "Exception raised!\nmodule 'hailstone4' has no attribute 'hailstone'", "At least one of our tests above found a problem."], "score_sum": 0, "max_score": 20}
{"info": {"start_time": "Sunday, 09. December 2018 05:26:56PM", "end_time": "Sunday, 09. December 2018 05:26:56PM", "timedelta": 0, "attempts": 1, "final score": 0, "max score": 20}, "internal_log": [], "external_log": ["Running test: hailstone(7)", "Exception raised!\nAn error occurred running hailstone(7)", "At least one of our tests above found a problem."], "score_sum": 0, "max_score": 20}
{"info": {"start_time": "Sunday, 09. December 2018 05:26:56PM", "end_time": "Sunday, 09. December 2018 05:26:56PM", "timedelta": 0, "attempts": 1, "final score": 20, "max score": 20}, "internal_log": [], "external_log": ["Running test: DrawDominoSet()", "Correct!", "Running test: Domino(3,5).getLeftDots()", "Correct!", "Running test: Domino(3,5).getRightDots()", "Correct!", "CONGRATULATIONS! All the tests passed."], "score_sum": 20, "max_score": 20}
{"info": {"start_time": "Sunday, 09. December 2018 05:26:56PM", "end_time": "Sunday, 09. December 2018 05:26:56PM", "timedelta": 0, "attempts": 1, "final score": 0, "max score": 20}, "internal_log": [], "external_log": ["Running test: DrawDominoSet()", "Correct!", "Running test: Domino(3,5).getLeftDots()", "Error in line 1:\n  We expected: 3\n  We received: 5", "At least one of our tests above found a problem."], "score_sum": 0, "max_score": 20}
{"info": {"start_time": "Sunday, 09. December 2018 05:26:57PM", "end_time": "Sunday, 09. December 2018 05:26:57PM", "timedelta": 0, "attempts": 1, "final score": 0, "max score": 20}, "internal_log": [], "external_log": ["Running test: DrawDominoSet()", "Correct!", "Running test: Domino(3,5).getLeftDots()", "Exception raised!\nGot no results from function call.", "At least one of our tests above found a problem."], "score_sum": 0, "max_score": 20}
{"info": {"start_time": "Sunday, 09. December 2018 05:26:57PM", "end_time": "Sunday, 09. December 2018 05:26:57PM", "timedelta": 0, "attempts": 1, "final score": 20, "max score": 20}, "internal_log": [], "external_log": ["Running test: two_largest.py with input (\"1\",\"2\",\"3\",\"4\",\"5\",\"\")", "Correct!", "Running test: two_largest.py with input (\"1\",\"2\",\"\")", "Correct!", "Running test: two_largest.py with input (\"32\",\"22\",\"123\",\"99\",\"2\",\"\")", "Correct!", "Running on a hidden test.", "Correct!", "Running on a hidden test.", "Correct!", "Running on a hidden test.", "Correct!", "Running on a hidden test.", "Correct!", "CONGRATULATIONS! All the tests passed."], "score_sum": 20, "max_score": 20}
{"info": {"start_time": "Sunday, 09. December 2018 05:26:57PM", "end_time": "Sunday, 09. December 2018 05:26:57PM", "timedelta": 0, "attempts": 1, "final score": 0, "max score": 20}, "internal_log": [], "external_log": ["Running test: two_largest2.py with input (\"1\",\"2\",\"3\",\"4\",\"5\",\"\")", "Error in line 3:\n  We expected: ?  ?  ?  ?  ?  ? The largest value is 5.\n  We received: ?  ?  ?  ?  ?  ? The largest value is 4.", "At least one of our tests above found a problem."], "score_sum": 0, "max_score": 20}
{"info": {"start_time": "Sunday, 09. December 2018 05:26:57PM", "end_time": "Sunday, 09. December 2018 05:26:57PM", "timedelta": 0, "attempts": 1, "final score": 0, "max score": 20}, "internal_log": [], "external_log": ["Running test: two_largest3.py with input (\"1\",\"2\",\"3\",\"4\",\"5\",\"\")", "Error in line 1:\n  We expected: This program finds the two largest integers.\n  We received: ", "At least one of our tests above found a problem."], "score_sum": 0, "max_score": 20}